name: Obica Server CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push image
      run:  |
        docker login --username biohazardious --password ${{ secrets.GH_PAT }} ghcr.io
        docker compose up --no-start --remove-orphans
        IMAGES=$(docker-compose images -q)
        
        echo "IMAGES: $IMAGES"
        
        for IMAGE in $IMAGES; do
            echo "IMAGE: $IMAGE"
            NAME=$(basename biohazardious).$(docker inspect --format '{{ index .RepoTags 0 }}' $IMAGE | awk -F ":" '{ print $1}')
            TAG="ghcr.io/biohazardious/$NAME:latest"
        
            docker tag $IMAGE $TAG
            docker push $TAG
        done
