name: Obico Server for GHCR

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  |
        docker login --username biohazardious --password ${{ secrets.GH_PAT }} ghcr.io
        docker compose tag --template "ghcr.io/biohazardious/obico-server:latest" --push
