name: Obica Server CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
#    - uses: actions/checkout@v3
#    - name: Build and Push image
#      run:  |
#        docker login --username biohazardious --password ${{ secrets.GH_PAT }} ghcr.io
#        docker compose tag --template "ghcr.io/biohazardious/obico-server:latest" --push
    - name: publish
      uses: soltys/publish-docker-compose@v1.0.0
      with:
        version: 'latest'
        docker_compose: 'docker-compose.yml'
        repo_token: "${{ secrets.GH_PAT }}"
